ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "acceptedTermsAt" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastOffersVisitAt" TEXT;
ALTER TABLE "Subscription" ADD COLUMN IF NOT EXISTS "voucherCode" TEXT;
ALTER TABLE "Subscription" ADD COLUMN IF NOT EXISTS "discountPercent" INTEGER;
ALTER TABLE "Subscription" ADD COLUMN IF NOT EXISTS "freeUntil" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "ownerUserId" TEXT;
CREATE TABLE IF NOT EXISTS "Voucher" (
  "id" TEXT PRIMARY KEY,
  "code" TEXT NOT NULL UNIQUE,
  "percent" INTEGER NOT NULL DEFAULT 100,
  "durationDays" INTEGER NOT NULL DEFAULT 30,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "note" TEXT,
  "maxRedemptions" INTEGER,
  "redeemedCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TEXT NOT NULL DEFAULT ''
);
